version: '3'
services:
  app1:
    restart: always
    image: freakston/upload-app:app1
    expose:
      - "6969"
  app2:
    restart: always
    image: freakston/register-app:app2
    expose:
      - "6968"
  app3:
    restart: always
    image: freakston/upload-app:app3
    expose:
      - "6970"
  nginx:
    restart: always
    image: freakston/nginx-app:nginx
    ports:
      - 8080:80
    links:
      - app1:app1
      - app2:app2
      - app3:app3